---
 - debug: msg="{{ lookup('env','HOME') }} is an environment variable"
 - name: Create a login user
   user:
     name: "{{ item.name }}"
     password: "{{ item.pass }}"
     update_password: on_create     
     groups: www-data,sudo   
     state: present
     shell: /bin/bash     
     createhome: yes        
     home: /home/{{ item.name }}
     append: yes
   with_items: "{{ consoleusers }}"

 - name: set Usersdirectory permission
   file:
     path: /home/{{ item.name }}
     owner: "{{ item.name }}"
     group: "{{ item.name }}"
     mode: 0775
   with_items: "{{ consoleusers }}"
   
 - name: Add .ssh directories
   file:
     path=/home/{{ item.name }}/.ssh
     state=directory
     mode=0700
     owner={{ item.name }}
     group={{ item.name }}  
   with_items: "{{ consoleusers }}"
   
 - name: Copy id_rsa.pub file
   template: 
     src: templates/keys/{{ item.name }}/id_rsa.pub
     dest: /home/{{ item.name }}/.ssh/id_rsa.pub
     owner: "{{ item.name }}"
     group: "{{ item.name }}"
     mode: '0644'
   with_items: "{{ consoleusers }}"
   
 - name: Copy id_rsa file
   template: 
     src: templates/keys/{{ item.name }}/id_rsa
     dest: /home/{{ item.name }}/.ssh/id_rsa
     owner: "{{ item.name }}"
     group: "{{ item.name }}"
     mode: '0600'
   with_items: "{{ consoleusers }}"   
   
 - name: Copy Root id_rsa.pub file
   template: 
     src: templates/keys/root/id_rsa.pub
     dest: /root/.ssh/id_rsa.pub
     owner: "root"
     group: "root"
     mode: '0644'
   
 - name: Copy Root id_rsa file
   template: 
     src: templates/keys/root/id_rsa
     dest: /root/.ssh/id_rsa
     owner: "root"
     group: "root"
     mode: '0600'  

 - name: Adding authorized keys
   template: 
     src: authorized_keys.j2
     dest: /home/{{ item.name }}/.ssh/authorized_keys
     owner: "{{ item.name }}"
     group: "{{ item.name }}"
     mode: '0644'
   with_items: "{{ consoleusers }}"   
  
   
 - name: Allow specified groups to sudo
   template: 
     src: sudoers.j2
     dest: /etc/sudoers.d/sudoers
     validate: 'visudo -cf %s'
     mode: 0440   
   
      
# - name: Copy authorized_keys file
#   copy: 
#     content: "{{ item.authorizedkeys }}"
#     dest: /home/{{ item.name }}/.ssh/authorized_keys
#     owner: "{{ item.name }}"
#     group: "{{ item.name }}"
#     mode: '0600'
#   with_items: "{{ consoleusers }}"