---
# created with:
# python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
consoleusers:


   - name: devop    
     pass: '$1$SomeSalt$Kc0U6cGbDTzN45eLUHsSI1'
     groups: 'www-data,adm,sudo'            
     authorizedkeys: 
       - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOgDH/6l1FoaYKAxd7b2gKZdUiYFCMN1voBL03uVhZVecQ72XUTRV0e3KlRcZSqoP2TaTB9lyTtvJPLA1G4Uf7qV/f/1l2Z+xRiv05ooghZFOXK+XzWEze81V1XBW3ehIURN58HtLChrvjL6TYuqFQsvAcTUdgYXVAeBDfzHqgzmIhlisKMRwpx6Yz3bNG4HprUPUL50oip2saxScFrYdUUk4tcL8OPZWRJNlkh2C5f4HNp9+ySYEfYKto9Nl2v1TtPmCVobtFmshRBgHstBNLRZ0sIAyhxAciqZLeW1OF/u2JQpnY7oW+euguiTUACSqk4dO8Bu/Avc3QQFCwgeK5y8NpMs5vNk3tYF6w1yWYEyquNj0GNoZhpQwAjy2d4Eg1n5pwhkSu3VHmD3GW3wSJwFvtoppnrCwVQKLTGvyqm3z12yInT37tX7zlD7b9YA/n68mW8jj8rhNSMxqMipNqTX05Scun/gFWoWmPMAsMaIsML47EpnkT/jd0L1FHsEbtPnwAtlSxbi9lmYkvfZhvnTfOCsEw5mbf/Ds1ZbocHgrwoNEmOSS5ADl7VKbcw/3436m8XgErsvfLNtEo9MtQHdr/78IMEla8EaTil9RUTs2cBw2PkepTO2DL9OIFZQhJLXmhun1zmv0J5e4msjr8YyGG+blTRXmb0ycyW/Jtuw== devop@chal-tec.com'
       - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDh9AL8LTVTCzelxD0FvgUkZpJEOGyrb1whXLZgaSsbYLyLBXIOPXapNUEOPhugAKQ4nFg7Yk4epIYGFVaFyQcNgow+VuNHqP50rXZ3qby9R0Cj04kBzcYJo/dmXtqJvGnnkShS39az0Q7LsHheuAQR86r3LR+JCaB7lnt70rwTpL4WKjhGrYWVpLdlbDSJErEo65V9epPVf6DJmtiiAlG7tpYHpAiW0V9KNOweE0ffAxrAk6C0048hwznWKr/aL5LQpgpq3zNi64Jxidy4sBTUEFbrUPa0Trln7rb5KBNtE7Lc5erWgegCqhSH8Y1DriZtbtd81EGiPTGs0wCprf+lHKcAcDehLWUpTteEeHSWcdKVBk6umMDUiwXHajNsJyF2qg0ZdJCh91GUPynCNHzZmdE4iUEjmz8DM/Zj6sGAkRH5HsmPFjuESS+lDrs7Pt+Grr19Sm1cnbnJV/6xxLFmsCqghYrhLbUQcuNXiM5MCAJIiYraD3QpJWwhsdCWzv8aB0dqFk7Esoka/wwEQIJqnh7ngxzAngbvF73TbhO+xWzTeUPX2GeJabBVihkB/tNoACXyRnLgPcQx4Ke5mdHNYqyv9fPVD36jkuElw4K8ZMKbYJPAOJ2W3JaFJcECIsaLpSXKCG5C9MexRsxAoTrc8s/0+Xz/4pQTfutENQbqZQ== sudouser@chal-tec.com'     
       

sudoers: 
   - devop
   - deployjenkins

