# created with:
# python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
consoleusers:
  - { name: "deployjenkins", pass: '$1$SomeSalt$E5QvexRmIXzQfikgTEiME0', pubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwLWnwVXjRPQ/UXs/FpUss3RWUZAsyJrX/Hbt4wFV3+ltlQcV3K/1EwFKcrEAOyLQyD4jomzkoTMa6zgIJC9yPpgvv3RPKn/ryfBXjPmj4NfNkiqiU2jTp0DhUW4MljTT9G2RsbYca7ly8DhwRQ7Qb6BoBLlvmwENtym0WTzmuqHepHPlFMTNkkYBkXqzkofaZxeGHEi7waXsVR4elL68EVliXPS++JLM4zCY9OyFRhA3p1Qef+gza7ObL5hWB2CHKQao5G5DgQ6goUw+IrdE7yrptZ0YlGn/GfUdTEQqo119aDXAldqGpvpxETKLFz1Ggcq7nW4VB7JynHDR1Ix5v devop@LnWebApp03
', privkey: '-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAsC1p8FV40T0P1F7PxaVLLN0VlGQLMia1/x27eMBVd/pbZUHF
dyv9RMBSnKxADsi0Mg+I6Js5KEzGus4CCQvcj6YL790Typ/68nwV4z5o+DXzZIqo
lNo06dA4VFuDJY00/RtkbG2HGu5cvA4cEUO0G+gaAS5b5sBDbcptFk85rqh3qRz5
RTEzZJGAZF6s5KH2mcXhhxIu8Gl7FUeHpS+vBFZYlz0vviSzOMwmPTshUYQN6dUH
n/oM2uzmy+YVgdghykGqORuQ4EOoKFMPiK3RO8q6bWdGJRp/xn1HUxEKqNdfWg1w
JXahqb6cREyixc9RoHKu51uFQeycpxw0dSMebwIDAQABAoIBAHiGqRodLyleL80n
C9d4LITFvzSkeLBXoVyl15JVamNJKGuOYmwT8RGuzRWYFb7Heddhn1UalDDIzZAQ
zX2o2rx/aV0wjpCpf8GSOFsdYCympBtdbNVgrqBirZawgHkZMG4T5lDzYWGAPnr8
4CDDg50v3VJ/h6nGUJr0yEph6uFcBoXjHzy4zy+Ep+3vldTL2yOUmLCvybhAWwNT
ONANv48byJGb4Mld8nWBlsOZmkd/0SEdgD9JF8+084X9YR1trE1xpZORGPtscrx2
dzKMFpW/mFMeY5g3qKjKcukIlc8weElmxmJoITohRx8I4EKnCL7PD/3LUts7+jvg
YJq3XckCgYEA32NDgiwpbvNBBa1MVHnW3pcW850sq7wfPfwWwftgJBlidwc0M5US
d5MamK+AFPaJrBG+ZeI2BA7jrcyphJgoVS/RUKb+fh5cDQUjyWQNQ203JS5yyC75
3EfhhRKhZxqNo3D16I9Py5U882F+kxUcjgHSaVbhTuo8jh7hun8O1lsCgYEAyeW+
ZOyeeozHj5ey7gkFI+bMTJS4aIWjL0+df3E8DHUYHhQuRJUbvDIWIruv25HvQArV
b1j6zW1qBpRgtWq2fKpBYAKduVJMSsoPERq8chemWcv+vLKRQRVKQ6C8M+yfyLle
bI4gX/QpxFZGVNPVupT13m25wNHZsiL3hqXfnH0CgYEA2bPGbc0WEA+29Y5fThBz
a/g5IO+zQiaTF/heQWv21Rd8E14M7JxCJBBToiufGk7t+qhMMsSTOb88+frz1cnn
vKVeS0iDymtR8EprBvCf0G9Wh8DNkfPeA2R2DxcJ/w4srPUAYkWQUWo+vT3tee/g
JTD3WzuVVjAHFcZY3ETJM/MCgYBD/LaJm9ieIgwNgaMCX0040r6XRzl2ERJrmx7J
TKNQ+pldf6Q4+hE15ZPorFVC1ji/0yYecdM7HA4pGwwZ6056WobbQuZEAr+oK7S5
KMyuiuI8uOIWPveE+Bti/JyDy7neyPVQDug+B6WM9RSH+jGtu/2zojV8Be6N+xJp
aDANrQKBgQCEq1cJUnd//Nqs42NMZxecFl5GYoR/uswWM56QEM2aRgti41dxfQxY
Ofhlxp8LdkTTd559Q15Nj3F7b/4SJP/nDv8BOmWH8rui1nXcFGrVW7kI53bhfZnY
hiQSHd4+cGR4KekpswsQLrzL+vZSTC1Ru7F0OIEYlOeUO7tFUNkA5A==
-----END RSA PRIVATE KEY----- ', authorizedkeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDi6hfz8cjLR8Ni4Y8RC0PsNFY3ll5eJuRBmRYWSKiNjRm2gSmIVDj24KdpNZZXWTA8bgH0Eoyxk3MiHxl3dBaNEpsNw4Y7yH6hVwizJzg/rxSKsHpFwDgOblMcytvXFrdi6p/axspUJ3wAuVoUhNSS3mK8DMqUudb+v6wbatvTDlMTsyvtZ3QXNxNSiYeaq3Yu46OaNB/uZrSEB2P7mZ5f53dxhT0j082kfQOwaNAjbrYbVtTpVI2UhOJvwTXP46IzRpiG2iuocWf96si5LxzSB6k7AD3WSOFCQLThbFtf+CC17zuBO2Sm5rMi8PaxyyYwA8Q4PWF/U4Et4ojrB3pr jenkins@LnJenkins03' }
  