- name: Install required packages with apt
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - build-essential
    - curl
    - git
    - htop
    - nano
    - unzip
    - vim
    - wget
    - tzdata

- name: Set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin


