# Setup/install tasks.
---
   
    - name: Create oxidee admin directory
      file:
        path:  /var/www/malls/{{ stage }}/{{ item.mall }}/htdocs/admin
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes
      with_items: "{{ malls }}"
      tags: 
      - oxidee  

    - name: 'copy config.inc.php file'
      template: src=config.inc.php.j2 dest=/var/www/malls/{{ stage }}/{{ item.mall }}/htdocs/config.inc.php
      with_items: "{{ malls }}" 
      tags: 
      - oxidee

    - name: 'copy  .htaccess file'
      template: src=.htaccess.j2 dest=/var/www/malls/{{ stage }}/{{ item.mall }}/htdocs/.htaccess
      with_items: "{{ malls }}" 
      tags: 
      - oxidee
 
    - name: 'copy admin .htaccess file'
      template: src=admin/.htaccess.j2 dest=/var/www/malls/{{ stage }}/{{ item.mall }}/htdocs/admin/.htaccess
      with_items: "{{ malls }}" 
      tags: 
      - oxidee


    - name: 'Create oxidee rest directory'
      file:
        path:  /var/www/malls/{{ stage }}/{{ item.mall }}/htdocs/rest
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes
      with_items: "{{ malls }}"
      tags: 
      - oxidee  

    - name: 'copy rest .htaccess file'
      template: src=rest/.htaccess.j2 dest=/var/www/malls/{{ stage }}/{{ item.mall }}/htdocs/rest/.htaccess
      with_items: "{{ malls }}" 
      tags: 
      - oxidee


    - name: 'Create oxidee wysiwigpro directory'
      file:
        path:  /var/www/malls/{{ stage }}/{{ item.mall }}/htdocs/core/wysiwigpro
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes
      with_items: "{{ malls }}"
      tags: 
      - oxidee  

    - name: 'copy wysiwigpro .confic.inc file'
      template: src=core/wysiwigpro/config.inc.php.j2 dest=/var/www/malls/{{ stage }}/{{ item.mall }}/htdocs/core/wysiwigpro/config.inc.php
      with_items: "{{ malls }}" 
      tags: 
      - oxidee
