# Setup/install tasks.
---
    - name: 'change hostname to {{inventory_hostname}}'
      hostname: 
        name: "{{inventory_hostname}}"
      when: inventory_hostname is defined and inventory_hostname != '' and inventory_hostname != None 
      tags: 
      - hostname       

    - name: 'add {{inventory_hostname}} to /etc/hosts'
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+{{ ansible_hostname }}'
        line: '127.0.0.1 {{inventory_hostname}}'
        state: present
      when: inventory_hostname is defined and inventory_hostname != '' and inventory_hostname != ''
      tags: 
      - hostname 