---
# tasks file for mysql
    - name: 'MySQL config file'
      template: src=my.cnf.j2 dest=/etc/mysql/mysql.conf.d/mysqld.cnf

    - name: 'Restart MySQL'
      service: name=mysql state=restarted
