---
- name: "Provision web nodes"
  hosts: webservers
  become: yes
  pre_tasks:
    - name: Add Apt PHP repository
      apt_repository:
        repo: ppa:ondrej/php
      tags: [php]
  roles:
    - { role: common, tags: [common] }
    - { role: apache, tags: [apache] }
    - { role: php, tags: [php] }
    - { role: composer, tags: [composer] }
    - { role: zend-guard-loader, tags: [zend-guard-loader] }
    - { role: xdebug, tags: [xdebug], when: enable_xdebug }
    - { role: configure-apache, tags: [configure-apache] }
  post_tasks:
    - name: Make xdebug file webserver writable
      file:
        path: /tmp/xdebug.log
        state: touch
        mode: 0777
      when: enable_xdebug
      tags: [xdebug]
