all:
  children:
    prod:
      children:
        unified_all:
          children:
            unified_prod:
              children:
                webservers:
                  hosts:
                    web1:
                      ansible_host: 10.100.2.241
                      ansible_ssh_user: ansiusr
                    web2:
                      ansible_host: 10.100.2.242
                      ansible_ssh_user: ansiusr
