---

- hosts: all
  roles:
    - users
    - bash-color-prompt
    
- hosts: MediaXX
  roles:
    - users
        
- hosts: productiondbservers
  roles:
    - mysql
    - zabbix-agent
    - hostname
    
- hosts: productionwebservers
  vars:    
    http_port: 80
  roles:
#    - gitShopsCerts  
    - users-sftp  
    - apache-2
    - php-5-6
    - zendguard    
    - erpcon
    - oxidee
    - zabbix-agent
    - hostname
    - awstats
            
- hosts: stagedbservers   
  roles:
    - mysql

- hosts: stagewebservers
  vars:    
    http_port: 80
  roles:
#    - gitShopsCerts
    - users-sftp
    - apache-2
    - php-5-6
    - zendguard
    - erpcon
    - oxidee


- hosts: dailydbservers
  roles:
    - mysql
    - zabbix-agent
    - hostname    

- hosts: dailywebservers
  vars:    
    http_port: 80
  roles:
#    - gitShopsCerts  
    - users-sftp  
    - apache-2
    - php-5-6
    - zendguard    
    - erpcon
    - oxidee
    - zabbix-agent
    - hostname
    - awstats
                
     
- hosts: devdbservers
  roles:
    - mysql
    - hostname
    
- hosts: devwebservers
  vars:    
    http_port: 80
  roles:
#    - gitShopsCerts  
    - users-sftp  
    - apache-2
    - php-5-6
    - zendguard    
    - erpcon
    - oxidee
    - hostname
    - awstats                