---

- hosts: all
  roles:
    - users
    - bash-color-prompt
    
- hosts: productiondbservers
  roles:
    - mysql

- hosts: productionwebservers
  vars:    
    http_port: 80
  roles:
    - apache-2
    - php-5-7
    - zendguard    
    
- hosts: stagedbservers   
  roles:
    - mysql

- hosts: stagewebservers
  vars:    
    http_port: 80
  roles:
    - apache-2
    - php-5-7
    - zendguard
    