---

- hosts: localhost
  gather_facts: true
  tasks: 

    - name: Execute the command in remote shell;
      shell:  whoami
      register: out
    - debug: var=out.stdout_lines

    - name: clone certificates Repo
      git:
        repo: git@LNAPP01:dev-ops/ShopCertificates.git
        version: master
        dest: /opt/private-repo/
        accept_hostkey: yes


- hosts: web
  become_method: sudo
  vars_files:
    - "environments/{{ env }}/group_vars/webserver.yml"

  vars:    
    http_port: 80
    domain: example.com
    vhost_sites:
      - {domain: "elektronik-star.de", mall: "estar"}
      - {domain: "electronic-star.sk", mall: "sk"}

  remote_user: devop

  tasks:

    - name: Copy SSL folder to server.
      copy:
        src: /opt/private-repo/ssl
        dest: /etc/apache2/
        mode: 0600
        owner: www-data
        group: www-data

    - service:
        name: apache2
        state: started
      become: yes
      become_method: sudo

  roles:
    - webservers
    - zend-guard-loader

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted