---

    - name: Create ssl directory
      file:
        path:  /etc/apache2/ssl
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes
      with_items: "{{ malls }}"
      tags: 
      - apache2    
      - apache2_certs
        

    
    # Synchronize two directories on one remote host.
    - synchronize:
        src: /var/www/ShopCertificates/ssl
        dest: /etc/apache2/
        owner: no
        group: no       
        recursive: yes
        delete: yes
        rsync_opts: ["--compress"]
        private_key : ~/.ssh/id_rsa
      tags: 
      - apache2    
      - apache2_certs      