---
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: Create apache2 vhosts
      template:
        src: templates/vhosts.conf.j2
        dest: /etc/apache2/sites-available/{{ subdomain }}.{{ item['domain'] }}.conf
      with_items: "{{ vhost_sites }}"
      
           
    - name: a2ensite {{ subdomain }}.{{ item['domain'] }}
      command: a2ensite {{ subdomain }}.{{ item['domain'] }}
      args:
        creates: /etc/apache2/sites-enabled/{{ subdomain }}.{{ item['domain'] }}}.conf
      with_items: "{{ vhost_sites }}"
      notify:
      - restart apache2
          