    - name: Create apache2 prefork Conf
      template:
        src: templates/mods-available/mpm_prefork.conf.j2
        dest: /etc/apache2/mods-enabled/mpm_prefork.conf       
      notify:
      - restart apache2
      tags: apache2

    