---
# tasks file for mysql
    - name: 'php config file'
      template: src=php.ini.j2 dest=/etc/php/5.6/apache2/php.ini
      tags: 
      - php 
      - php5.6 
    
# tasks file for mysql
    - name: 'php fpm config file'
      template: src=fpm/php.ini.j2 dest=/etc/php/5.6/fpm/php.ini
      tags: 
      - php 
      - php5.6 
      - php5.5-fpm      
    
# tasks file for mysql
    - name: 'php cli config file'
      template: src=cli/php.ini.j2 dest=/etc/php/5.6/cli/php.ini
      tags: 
      - php 
      - php5.6 
      - php5.5-cli  

    - name: 'Restart apache2'
      service: 
        name: apache2 
        state: restarted