- name: Check if Zend Guard installed
  command: php -m | grep "Zend Guard Loader"
  register: php_m_cmd
  changed_when: False

- name: Copy Zend Guard Loader archive to remote
  copy:
    src: "module/{{ php_zend_guard_archive_file_name }}"
    dest: "{{ php_zend_guard_extension_directory }}/zend-guard.tar.gz"
    mode: 0644
  when: php_m_cmd.stdout is not search("Zend Guard Loader")

- name: Extract Zend Guard Loader
  unarchive:
    src: "{{ php_zend_guard_extension_directory }}/zend-guard.tar.gz"
    dest: "{{ php_zend_guard_extension_directory }}"
    mode: 0644
  when: php_m_cmd.stdout is not search("Zend Guard Loader")

- name: Move Zend Guard Loader module into place
  command: "mv {{ php_zend_guard_extension_directory }}/zend-loader-php5.6-linux-x86_64/ZendGuardLoader.so {{ php_zend_guard_extension_directory }}/ZendGuardLoader.so"
  when: php_m_cmd.stdout is not search("Zend Guard Loader")
  notify: restart webserver

- name: Clean up the Zend Guard extension directory
  file:
    state: absent
    path: "{{ php_zend_guard_extension_directory }}/{{ item }}"
  with_items:
    - zend-guard.tar.gz
    - zend-loader-php5.6-linux-x86_64
  when: php_m_cmd.stdout is not search("Zend Guard Loader")

- name: Copy Zend Guard Loader ini into main extension config folders.
  template:
    src: zend-guard-loader.ini.j2
    dest: "{{ item }}/{{ php_zend_guard_config_filename }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ php_extension_conf_paths }}"
  notify:
    - restart webserver
    - restart php-fpm
